use crate::error::InlaError;
use crate::graph::Graph;
use crate::models::QFunc;
use crate::solver::{FaerSolver, SparseSolver};

pub const PRIOR_PREC_BETA: f64 = 0.001;

pub struct Problem {
    graph:   Graph,
    pub(crate) solver:  FaerSolver,
    log_det: f64,
    pub n_evals: usize,
}

impl Problem {
    pub fn new(model: &crate::inference::InlaModel<'_>) -> Self {
        let mut graph  = model.qfunc.graph().clone();
        
        // Merge the connections generated by A^T A (Random effects interacting via the same Observation rows)
        if let (Some(a_i), Some(a_j)) = (model.a_i, model.a_j) {
            let a_edges = Graph::build_a_t_a_edges(a_i, a_j, model.y.len());
            graph.merge_edges(&a_edges);
        }
        
        let mut solver = FaerSolver::new();
        solver.reorder(&mut graph);
        Self { graph, solver, log_det: 0.0, n_evals: 0 }
    }

    pub fn eval(&mut self, qfunc: &dyn QFunc, theta: &[f64]) -> Result<f64, InlaError> {
        self.solver.build(&self.graph, qfunc, theta);
        self.solver.factorize()?;
        self.log_det = self.solver.log_determinant();
        self.n_evals += 1;
        Ok(self.log_det)
    }

    pub fn eval_with_inverse(
        &mut self,
        qfunc: &dyn QFunc,
        theta: &[f64],
    ) -> Result<(f64, Vec<f64>), InlaError> {
        self.solver.build(&self.graph, qfunc, theta);
        self.solver.factorize()?;
        let log_det  = self.solver.log_determinant();
        self.log_det  = log_det;
        self.n_evals += 1;

        let q_inv    = self.solver.selected_inverse()?;
        let col_ptr  = q_inv.symbolic().col_ptr();
        let row_idx  = q_inv.symbolic().row_idx();
        let all_vals = q_inv.val();

        let n = self.n();
        let diag_qinv: Vec<f64> = (0..n)
            .map(|j| {
                let start    = col_ptr[j];
                let end      = col_ptr[j + 1];
                let col_rows = &row_idx[start..end];
                let pos      = col_rows.binary_search(&j).unwrap();
                all_vals[start + pos]
            })
            .collect();

        Ok((log_det, diag_qinv))
    }

    pub fn find_mode_with_inverse(
        &mut self,
        qfunc:      &dyn QFunc,
        likelihood: &dyn crate::likelihood::LogLikelihood,
        y:          &[f64],
        a_i: Option<&[usize]>, a_j: Option<&[usize]>, a_x: Option<&[f64]>, offset: Option<&[f64]>,
        theta:      &[f64],
        x_init:     &[f64],
        max_iter:   usize,
        tol:        f64,
    ) -> Result<(Vec<f64>, f64, Vec<f64>), InlaError> {
        let n_latent    = self.n();
        let n_data      = y.len();
        let n_model     = qfunc.n_hyperparams();
        let theta_model = &theta[..n_model];
        let theta_lik   = &theta[n_model..];
        
        let mut x = if x_init.len() == n_latent { x_init.to_vec() } else { vec![0.0_f64; n_latent] };
        let mut log_det_aug = 0.0_f64;

        for _iter in 0..max_iter {
            let x_old = x.clone();

            let mut eta_data = vec![0.0_f64; n_data];
            for i in 0..n_data {
                let lat_i = a_i.map_or(i, |idx| idx[i]);
                eta_data[i] = x[lat_i];
            }

            let mut grad_data = vec![0.0_f64; n_data];
            let mut curv_data = vec![0.0_f64; n_data];
            likelihood.gradient_and_curvature(&mut grad_data, &mut curv_data, &eta_data, y, theta_lik);
            
            for i in 0..n_data { curv_data[i] = curv_data[i].max(1e-6); }

            let mut grad_latent = vec![0.0_f64; n_latent];
            let mut curv_latent = vec![0.0_f64; n_latent];
            for i in 0..n_data {
                let lat_i = a_i.map_or(i, |idx| idx[i]);
                grad_latent[lat_i] += grad_data[i];
                curv_latent[lat_i] += curv_data[i];
            }
            for k in 0..n_latent { curv_latent[k] = curv_latent[k].max(1e-6); }

            let z_latent: Vec<f64> = (0..n_latent).map(|k| x[k] + grad_latent[k] / curv_latent[k]).collect();
            let mut rhs: Vec<f64>  = (0..n_latent).map(|k| curv_latent[k] * z_latent[k]).collect();

            let aug = AugmentedQFunc { inner: qfunc, diag_add: &curv_latent };
            self.solver.build(&self.graph, &aug, theta_model);
            self.solver.factorize()?;
            log_det_aug = self.solver.log_determinant();
            self.solver.solve_llt(&mut rhs);
            x = rhs;

            let delta: f64 = x.iter().zip(x_old.iter()).map(|(a, b)| (a - b).abs()).fold(0.0_f64, f64::max);
            if delta < tol { break; }
        }

        let aug_inv  = self.solver.selected_inverse()?;
        let col_ptr  = aug_inv.symbolic().col_ptr();
        let row_idx  = aug_inv.symbolic().row_idx();
        let all_vals = aug_inv.val();

        let diag_aug_inv: Vec<f64> = (0..n_latent).map(|j| {
            let pos = row_idx[col_ptr[j]..col_ptr[j + 1]].binary_search(&j).unwrap();
            all_vals[col_ptr[j] + pos]
        }).collect();

        Ok((x, log_det_aug, diag_aug_inv))
    }

    /// Implements the General Fixed Effects Solver via Matrix Schur Complement
    /// Replaces beta0 with a K-dimensional vector beta.
    pub fn find_mode_with_fixed_effects(
        &mut self,
        qfunc:      &dyn QFunc,
        likelihood: &dyn crate::likelihood::LogLikelihood,
        y:          &[f64],
        a_i: Option<&[usize]>, a_j: Option<&[usize]>, a_x: Option<&[f64]>, offset: Option<&[f64]>,
        x_mat:      Option<&[f64]>,
        n_fixed:    usize,
        theta:      &[f64],
        x_init:     &[f64],
        beta_init:  &[f64],
        max_iter:   usize,
        tol:        f64,
    ) -> Result<(Vec<f64>, Vec<f64>, f64, Vec<f64>, f64), InlaError> {
        if n_fixed == 0 || x_mat.is_none() {
            let (x, ld, di) = self.find_mode_with_inverse(qfunc, likelihood, y, a_i, theta, x_init, max_iter, tol)?;
            return Ok((vec![], x, ld, di, 0.0));
        }
        
        let x_m = x_mat.unwrap();
        let n_latent    = self.n();
        let n_data      = y.len();
        let n_model     = qfunc.n_hyperparams();
        let theta_model = &theta[..n_model];
        let theta_lik   = &theta[n_model..];

        let mut x = if x_init.len() == n_latent { x_init.to_vec() } else { vec![0.0_f64; n_latent] };
        let mut beta = if beta_init.len() == n_fixed { beta_init.to_vec() } else { vec![0.0_f64; n_fixed] };
        
        let mut log_det_aug = 0.0_f64;
        let mut final_w_cross = vec![0.0_f64; n_latent * n_fixed];
        let mut final_w_data  = vec![0.0_f64; n_data];

        for _iter in 0..max_iter {
            let x_old     = x.clone();
            let beta_old  = beta.clone();

            let mut eta_data = vec![0.0_f64; n_data];
            for i in 0..n_data {
                let mut xb = 0.0;
                for j in 0..n_fixed { xb += x_m[i + j * n_data] * beta[j]; }
                let lat_i = a_i.map_or(i, |idx| idx[i]);
                eta_data[i] = xb + x[lat_i] + offset.map_or(0.0, |offs| offs[i]);
            }

            let mut grad_data = vec![0.0_f64; n_data];
            let mut curv_data = vec![0.0_f64; n_data];
            likelihood.gradient_and_curvature(&mut grad_data, &mut curv_data, &eta_data, y, theta_lik);
            
            for i in 0..n_data { curv_data[i] = curv_data[i].max(1e-6); }
            final_w_data = curv_data.clone();

            let mut grad_latent = vec![0.0_f64; n_latent];
            let mut curv_latent = vec![0.0_f64; n_latent];
            for i in 0..n_data {
                let lat_i = a_i.map_or(i, |idx| idx[i]);
                grad_latent[lat_i] += grad_data[i];
                curv_latent[lat_i] += curv_data[i];
            }
            for k in 0..n_latent { curv_latent[k] = curv_latent[k].max(1e-6); }

            // W_cross = A^T W_data X
            let mut w_cross = vec![0.0_f64; n_latent * n_fixed];
            for j in 0..n_fixed {
                for i in 0..n_data {
                    let lat_i = a_i.map_or(i, |idx| idx[i]);
                    w_cross[lat_i + j * n_latent] += curv_data[i] * x_m[i + j * n_data];
                }
            }
            final_w_cross = w_cross.clone();

            // z_data = eta + grad/curv => b_beta = X^T W z_data, b_x = A^T W z_data
            let mut b_beta = vec![0.0_f64; n_fixed];
            let mut b_x    = vec![0.0_f64; n_latent];
            for i in 0..n_data {
                let z_i = eta_data[i] + grad_data[i] / curv_data[i];
                let wz  = curv_data[i] * z_i;
                for j in 0..n_fixed { b_beta[j] += x_m[i + j * n_data] * wz; }
                let lat_i = a_i.map_or(i, |idx| idx[i]);
                b_x[lat_i] += wz;
            }

            self.solver.build(&self.graph, &AugmentedQFunc { inner: qfunc, diag_add: &curv_latent }, theta_model);
            self.solver.factorize()?;
            log_det_aug = self.solver.log_determinant();
            
            // Generate u = (Q+W)^-1 b_x
            let mut u = b_x.clone();
            self.solver.solve_llt(&mut u);

            // Generate dense V = (Q+W)^-1 W_cross
            let mut v = vec![0.0_f64; n_latent * n_fixed];
            for j in 0..n_fixed {
                let mut v_col = w_cross[j * n_latent .. (j+1) * n_latent].to_vec();
                self.solver.solve_llt(&mut v_col);
                for k in 0..n_latent { v[k + j * n_latent] = v_col[k]; }
            }

            let mut s_mat = vec![0.0_f64; n_fixed * n_fixed];
            for j1 in 0..n_fixed {
                for j2 in 0..n_fixed {
                    let mut xtwx = 0.0;
                    for i in 0..n_data {
                        xtwx += x_m[i + j1 * n_data] * curv_data[i] * x_m[i + j2 * n_data];
                    }
                    if j1 == j2 { xtwx += PRIOR_PREC_BETA; }
                    
                    let mut wcv = 0.0;
                    for k in 0..n_latent {
                        wcv += w_cross[k + j1 * n_latent] * v[k + j2 * n_latent];
                    }
                    s_mat[j1 * n_fixed + j2] = xtwx - wcv;
                }
            }

            // RHS vector b_s = b_beta - W_cross^T u
            let mut b_s = vec![0.0_f64; n_fixed];
            for j in 0..n_fixed {
                let mut wcu = 0.0;
                for k in 0..n_latent { wcu += w_cross[k + j * n_latent] * u[k]; }
                b_s[j] = b_beta[j] - wcu;
            }

            // Solve dense Schur system natively (O(K^3))
            dense_cholesky_solve(&mut s_mat, &mut b_s, n_fixed)?;
            for j in 0..n_fixed { beta[j] = b_s[j]; }

            // x = u - V beta
            for k in 0..n_latent {
                let mut vb = 0.0;
                for j in 0..n_fixed { vb += v[k + j * n_latent] * beta[j]; }
                x[k] = u[k] - vb;
            }

            let mut delta_max = 0.0_f64;
            for (a, b_val) in x.iter().zip(x_old.iter()) { delta_max = delta_max.max((a - b_val).abs()); }
            for (a, b_val) in beta.iter().zip(beta_old.iter()) { delta_max = delta_max.max((a - b_val).abs()); }
            
            if delta_max < tol { break; }
        }

        let aug_inv  = self.solver.selected_inverse()?;
        let col_ptr  = aug_inv.symbolic().col_ptr();
        let row_idx  = aug_inv.symbolic().row_idx();
        let all_vals = aug_inv.val();

        let diag_aug_inv: Vec<f64> = (0..n_latent).map(|j| {
            let pos = row_idx[col_ptr[j]..col_ptr[j + 1]].binary_search(&j).unwrap();
            all_vals[col_ptr[j] + pos]
        }).collect();

        // Compute log det of final Schur matrix S for penalizing marginal likelihood
        let mut v = vec![0.0_f64; n_latent * n_fixed];
        for j in 0..n_fixed {
            let mut v_col = final_w_cross[j * n_latent .. (j+1) * n_latent].to_vec();
            self.solver.solve_llt(&mut v_col);
            for k in 0..n_latent { v[k + j * n_latent] = v_col[k]; }
        }

        let mut s_mat = vec![0.0_f64; n_fixed * n_fixed];
        for j1 in 0..n_fixed {
            for j2 in 0..n_fixed {
                let mut xtwx = 0.0;
                for i in 0..n_data {
                    xtwx += x_m[i + j1 * n_data] * final_w_data[i] * x_m[i + j2 * n_data];
                }
                if j1 == j2 { xtwx += PRIOR_PREC_BETA; }
                let mut wcv = 0.0;
                for k in 0..n_latent {
                    wcv += final_w_cross[k + j1 * n_latent] * v[k + j2 * n_latent];
                }
                s_mat[j1 * n_fixed + j2] = xtwx - wcv;
            }
        }
        
        let mut dummy_b = vec![0.0_f64; n_fixed];
        let schur_log_det = dense_cholesky_solve(&mut s_mat, &mut dummy_b, n_fixed)?;

        Ok((beta, x, log_det_aug, diag_aug_inv, schur_log_det))
    }

    pub fn find_mode_with_logdet(&mut self, qfunc: &dyn QFunc, likelihood: &dyn crate::likelihood::LogLikelihood, y: &[f64], a_i: Option<&[usize]>, a_j: Option<&[usize]>, a_x: Option<&[f64]>, offset: Option<&[f64]>, theta: &[f64], max_iter: usize, tol: f64) -> Result<(Vec<f64>, f64), InlaError> {
        let (x, ld, _) = self.find_mode_with_inverse(qfunc, likelihood, y, a_i, theta, &[], max_iter, tol)?;
        Ok((x, ld))
    }

    pub fn find_mode(&mut self, qfunc: &dyn QFunc, likelihood: &dyn crate::likelihood::LogLikelihood, y: &[f64], a_i: Option<&[usize]>, a_j: Option<&[usize]>, a_x: Option<&[f64]>, offset: Option<&[f64]>, theta: &[f64], max_iter: usize, tol: f64) -> Result<Vec<f64>, InlaError> {
        let (x, _) = self.find_mode_with_logdet(qfunc, likelihood, y, a_i, theta, max_iter, tol)?;
        Ok(x)
    }

    pub fn solve(&self, rhs: &mut [f64]) { self.solver.solve_llt(rhs); }
    pub fn log_det(&self) -> f64 { self.log_det }
    pub fn n(&self) -> usize { self.graph.n() }

    pub fn quadratic_form_x(&self, qfunc: &dyn QFunc, theta_model: &[f64], x: &[f64]) -> f64 {
        let n = self.n();
        let diag: f64 = (0..n).map(|i| qfunc.eval(i, i, theta_model) * x[i] * x[i]).sum();
        let offdiag: f64 = self.graph.iter_upper_triangle().map(|(i, j)| 2.0 * qfunc.eval(i, j, theta_model) * x[i] * x[j]).sum();
        diag + offdiag
    }
}

// Native dense Cholesky implementation for tiny exact K x K matrices.
fn dense_cholesky_solve(a: &mut [f64], b: &mut [f64], n: usize) -> Result<f64, InlaError> {
    let mut log_det = 0.0;
    for i in 0..n {
        for j in 0..=i {
            let mut sum = a[i * n + j];
            for k in 0..j { sum -= a[i * n + k] * a[j * n + k]; }
            if i == j {
                if sum <= 0.0 { return Err(InlaError::NotPositiveDefinite); }
                let l_ii = sum.sqrt();
                a[i * n + j] = l_ii;
                log_det += 2.0 * l_ii.ln();
            } else {
                a[i * n + j] = sum / a[j * n + j];
            }
        }
    }
    for i in 0..n {
        let mut sum = b[i];
        for k in 0..i { sum -= a[i * n + k] * b[k]; }
        b[i] = sum / a[i * n + i];
    }
    for i in (0..n).rev() {
        let mut sum = b[i];
        for k in (i + 1)..n { sum -= a[k * n + i] * b[k]; }
        b[i] = sum / a[i * n + i];
    }
    Ok(log_det)
}

struct AugmentedQFunc<'a> {
    inner:    &'a dyn QFunc,
    diag_add: &'a [f64],
}

impl QFunc for AugmentedQFunc<'_> {
    fn graph(&self) -> &Graph { self.inner.graph() }
    fn eval(&self, i: usize, j: usize, theta: &[f64]) -> f64 {
        let base = self.inner.eval(i, j, theta);
        if i == j { base + self.diag_add[i] } else { base }
    }
    fn n_hyperparams(&self) -> usize { self.inner.n_hyperparams() }
}
