use crate::error::InlaError;
use crate::graph::Graph;
use crate::models::QFunc;
use crate::solver::{FaerSolver, SparseSolver};

pub const PRIOR_PREC_BETA: f64 = 0.001;

pub struct Problem {
    graph:   Graph,
    pub(crate) solver:  FaerSolver,
    log_det: f64,
    pub n_evals: usize,
}

impl Problem {
    pub fn new(model: &crate::inference::InlaModel<'_>) -> Self {
        let mut graph  = model.qfunc.graph().clone();
        
        // Merge the connections generated by A^T A (Random effects interacting via the same Observation rows)
        if let (Some(a_i), Some(a_j)) = (model.a_i, model.a_j) {
            let a_edges = Graph::build_a_t_a_edges(a_i, a_j, model.y.len());
            graph.merge_edges(&a_edges);
        }
        
        let mut solver = FaerSolver::new();
        solver.reorder(&mut graph);
        Self { graph, solver, log_det: 0.0, n_evals: 0 }
    }

    pub fn eval(&mut self, qfunc: &dyn QFunc, theta: &[f64]) -> Result<f64, InlaError> {
        self.solver.build(&self.graph, qfunc, theta);
        self.solver.factorize().map_err(|_| crate::error::InlaError::NotPositiveDefiniteContext("Problem::eval Q factorize failed".to_string()))?;
        self.log_det = self.solver.log_determinant();
        self.n_evals += 1;
        Ok(self.log_det)
    }

    pub fn eval_with_inverse(
        &mut self,
        qfunc: &dyn QFunc,
        theta: &[f64],
    ) -> Result<(f64, Vec<f64>), InlaError> {
        self.solver.build(&self.graph, qfunc, theta);
        self.solver.factorize().map_err(|_| crate::error::InlaError::NotPositiveDefiniteContext("Q prior factorize failed".to_string()))?;
        let log_det  = self.solver.log_determinant();
        self.log_det  = log_det;
        self.n_evals += 1;

        let q_inv    = self.solver.selected_inverse()?;
        let col_ptr  = q_inv.symbolic().col_ptr();
        let row_idx  = q_inv.symbolic().row_idx();
        let all_vals = q_inv.val();

        let n = self.n();
        let diag_qinv: Vec<f64> = (0..n)
            .map(|j| {
                let start    = col_ptr[j];
                let end      = col_ptr[j + 1];
                let col_rows = &row_idx[start..end];
                let pos      = col_rows.binary_search(&j).unwrap();
                all_vals[start + pos]
            })
            .collect();

        Ok((log_det, diag_qinv))
    }

    pub fn find_mode_with_inverse(
        &mut self,
        model:      &crate::inference::InlaModel<'_>,
        theta:      &[f64],
        x_init:     &[f64],
        max_iter:   usize,
        tol:        f64,
    ) -> Result<(Vec<f64>, f64, Vec<f64>), InlaError> {
        let n_latent    = self.n();
        let n_data      = model.y.len();
        let n_model     = model.qfunc.n_hyperparams();
        let theta_model = &theta[..n_model];
        let theta_lik   = &theta[n_model..];
        
        let mut x = if x_init.len() == n_latent { x_init.to_vec() } else { vec![0.0_f64; n_latent] };
        let mut log_det_aug = 0.0_f64;

        let mut a_rows = vec![vec![]; n_data];
        if let (Some(a_i), Some(a_j), Some(a_x)) = (model.a_i, model.a_j, model.a_x) {
            for k in 0..a_i.len() { a_rows[a_i[k]].push((a_j[k], a_x[k])); }
        } else {
            for i in 0..n_data.min(n_latent) { a_rows[i].push((i, 1.0)); }
        }

        for _iter in 0..max_iter {
            let x_old = x.clone();

            let mut eta_data = vec![0.0_f64; n_data];
            for i in 0..n_data {
                for &(j, ax) in &a_rows[i] { eta_data[i] += ax * x[j]; }
            }
            if let Some(offset) = model.offset {
                for i in 0..n_data { eta_data[i] += offset[i]; }
            }

            let mut grad_data = vec![0.0_f64; n_data];
            let mut curv_data = vec![0.0_f64; n_data];
            model.likelihood.gradient_and_curvature(&mut grad_data, &mut curv_data, &eta_data, model.y, theta_lik);
            
            for i in 0..n_data { curv_data[i] = curv_data[i].max(1e-6); }

            let mut grad_latent = vec![0.0_f64; n_latent];
            for i in 0..n_data {
                for &(j, ax) in &a_rows[i] { grad_latent[j] += ax * grad_data[i]; }
            }

            let mut atwa = std::collections::HashMap::new();
            for i in 0..n_data {
                let w = curv_data[i];
                let row = &a_rows[i];
                for &(j1, ax1) in row {
                    for &(j2, ax2) in row {
                        let (min_j, max_j) = if j1 < j2 { (j1, j2) } else { (j2, j1) };
                        *atwa.entry((min_j, max_j)).or_insert(0.0) += ax1 * w * ax2;
                    }
                }
            }

            // z = x + Q_aug^-1 grad => Q_aug x + grad
            let mut rhs = vec![0.0_f64; n_latent];
            for k in 0..n_latent {
                rhs[k] = grad_latent[k] + model.qfunc.eval(k, k, theta_model) * x[k] + atwa.get(&(k, k)).copied().unwrap_or(0.0) * x[k];
                for &neighbor in self.graph.neighbors_of(k) {
                    if neighbor != k {
                        let q_ij = model.qfunc.eval(k, neighbor, theta_model);
                        let (min_j, max_j) = if k < neighbor { (k, neighbor) } else { (neighbor, k) };
                        let atwa_ij = atwa.get(&(min_j, max_j)).copied().unwrap_or(0.0);
                        rhs[k] += (q_ij + atwa_ij) * x[neighbor];
                    }
                }
            }

            let aug = AugmentedQFunc { inner: model.qfunc, atwa: &atwa };
            self.solver.build(&self.graph, &aug, theta_model);
            self.solver.factorize().map_err(|_| crate::error::InlaError::NotPositiveDefiniteContext("Sparse Q_aug block 1 singular".to_string()))?;
            log_det_aug = self.solver.log_determinant();
            self.solver.solve_llt(&mut rhs);
            x = rhs;

            let delta: f64 = x.iter().zip(x_old.iter()).map(|(a, b)| (a - b).abs()).fold(0.0_f64, f64::max);
            if delta < tol { break; }
        }

        let aug_inv  = self.solver.selected_inverse()?;
        let col_ptr  = aug_inv.symbolic().col_ptr();
        let row_idx  = aug_inv.symbolic().row_idx();
        let all_vals = aug_inv.val();

        let diag_aug_inv: Vec<f64> = (0..n_latent).map(|j| {
            let pos = row_idx[col_ptr[j]..col_ptr[j + 1]].binary_search(&j).unwrap();
            all_vals[col_ptr[j] + pos]
        }).collect();

        Ok((x, log_det_aug, diag_aug_inv))
    }

    /// Implements the General Fixed Effects Solver via Matrix Schur Complement
    /// Replaces beta0 with a K-dimensional vector beta.
    pub fn find_mode_with_fixed_effects(
        &mut self,
        model:      &crate::inference::InlaModel<'_>,
        theta:      &[f64],
        x_init:     &[f64],
        beta_init:  &[f64],
        max_iter:   usize,
        tol:        f64,
    ) -> Result<(Vec<f64>, Vec<f64>, f64, Vec<f64>, f64), InlaError> {
        if model.n_fixed == 0 || model.fixed_matrix.is_none() {
            let (x, ld, di) = self.find_mode_with_inverse(model, theta, x_init, max_iter, tol)?;
            return Ok((vec![], x, ld, di, 0.0));
        }
        
        let x_m = model.fixed_matrix.unwrap();
        let n_fixed = model.n_fixed;
        let n_latent    = self.n();
        let n_data      = model.y.len();
        let n_model     = model.qfunc.n_hyperparams();
        let theta_model = &theta[..n_model];
        let theta_lik   = &theta[n_model..];

        let mut x = if x_init.len() == n_latent { x_init.to_vec() } else { vec![0.0_f64; n_latent] };
        let mut beta = if beta_init.len() == n_fixed { beta_init.to_vec() } else { vec![0.0_f64; n_fixed] };
        
        let mut log_det_aug = 0.0_f64;
        let mut final_w_cross = vec![0.0_f64; n_latent * n_fixed];
        let mut final_w_data  = vec![0.0_f64; n_data];

        let mut a_rows = vec![vec![]; n_data];
        if let (Some(a_i), Some(a_j), Some(a_x)) = (model.a_i, model.a_j, model.a_x) {
            for k in 0..a_i.len() { a_rows[a_i[k]].push((a_j[k], a_x[k])); }
        } else {
            for i in 0..n_data.min(n_latent) { a_rows[i].push((i, 1.0)); }
        }

        for _iter in 0..max_iter {
            let x_old     = x.clone();
            let beta_old  = beta.clone();

            let mut eta_data = vec![0.0_f64; n_data];
            for i in 0..n_data {
                for &(j, ax) in &a_rows[i] { eta_data[i] += ax * x[j]; }
                let mut xb = 0.0;
                for j in 0..n_fixed { xb += x_m[i + j * n_data] * beta[j]; }
                eta_data[i] += xb;
            }
            if let Some(offset) = model.offset {
                for i in 0..n_data { eta_data[i] += offset[i]; }
            }

            let mut grad_data = vec![0.0_f64; n_data];
            let mut curv_data = vec![0.0_f64; n_data];
            model.likelihood.gradient_and_curvature(&mut grad_data, &mut curv_data, &eta_data, model.y, theta_lik);
            
            for i in 0..n_data { curv_data[i] = curv_data[i].max(1e-6); }
            final_w_data = curv_data.clone();

            let mut grad_latent = vec![0.0_f64; n_latent];
            for i in 0..n_data {
                for &(j, ax) in &a_rows[i] { grad_latent[j] += ax * grad_data[i]; }
            }

            let mut atwa = std::collections::HashMap::new();
            for i in 0..n_data {
                let w = curv_data[i];
                let row = &a_rows[i];
                for &(j1, ax1) in row {
                    for &(j2, ax2) in row {
                        if j1 <= j2 {
                            *atwa.entry((j1, j2)).or_insert(0.0) += ax1 * w * ax2;
                        }
                    }
                }
            }

            let mut w_cross = vec![0.0_f64; n_latent * n_fixed];
            for i in 0..n_data {
                for j in 0..n_fixed {
                    let w_x_m = curv_data[i] * x_m[i + j * n_data];
                    for &(k, ax) in &a_rows[i] {
                        w_cross[k + j * n_latent] += ax * w_x_m;
                    }
                }
            }
            final_w_cross = w_cross.clone();

            let mut b_beta = vec![0.0_f64; n_fixed];
            let mut b_x    = vec![0.0_f64; n_latent];
            
            let mut wz_data = vec![0.0_f64; n_data];
            for i in 0..n_data {
                let z_i = eta_data[i] + grad_data[i] / curv_data[i];
                wz_data[i] = curv_data[i] * z_i;
                for j in 0..n_fixed { b_beta[j] += x_m[i + j * n_data] * wz_data[i]; }
                for &(k, ax) in &a_rows[i] { b_x[k] += ax * wz_data[i]; }
            }

            let aug = AugmentedQFunc { inner: model.qfunc, atwa: &atwa };
            self.solver.build(&self.graph, &aug, theta_model);
            
            self.solver.factorize().map_err(|_| crate::error::InlaError::NotPositiveDefiniteContext(format!("Sparse Q_aug block 2 singular at iter {}", _iter)))?;

            log_det_aug = self.solver.log_determinant();
            
            let mut u = b_x.clone();
            self.solver.solve_llt(&mut u);

            let mut v = vec![0.0_f64; n_latent * n_fixed];
            for j in 0..n_fixed {
                let mut v_col = w_cross[j * n_latent .. (j+1) * n_latent].to_vec();
                self.solver.solve_llt(&mut v_col);
                for k in 0..n_latent { v[k + j * n_latent] = v_col[k]; }
            }
            
            // KKT Kriging Core
            if let Some(constr) = model.extr_constr {
                let n_c = model.n_constr;
                if n_c > 0 {
                    let mut v_c = vec![0.0_f64; n_latent * n_c];
                    for c in 0..n_c {
                        let mut vc_col = constr[c * n_latent .. (c+1) * n_latent].to_vec();
                        self.solver.solve_llt(&mut vc_col);
                        for k in 0..n_latent { v_c[c * n_latent + k] = vc_col[k]; }
                    }
                    
                    let mut c_vc = vec![0.0_f64; n_c * n_c];
                    for c1 in 0..n_c {
                        for c2 in 0..n_c {
                            for k in 0..n_latent {
                                c_vc[c1 * n_c + c2] += constr[c1 * n_latent + k] * v_c[c2 * n_latent + k];
                            }
                        }
                    }
                    
                    let mut c_vc_inv = c_vc.clone();
                    let mut dummy_b = vec![0.0_f64; n_c]; 
                    if let Err(_) = dense_cholesky_solve(&mut c_vc_inv, &mut dummy_b, n_c) {
                        return Err(crate::error::InlaError::NotPositiveDefiniteContext("Kriging C V_c block singular".to_string()));
                    } else {
                        // We must compute matrix inverse from the packed cholesky representation.
                        // Actually dense_cholesky_solve returns L in lower triangle.
                        // For simplicity, let's just do a poor-man's dense inverse by solving identity vectors.
                        let mut real_inv = vec![0.0_f64; n_c * n_c];
                        for c in 0..n_c {
                            let mut e = vec![0.0_f64; n_c];
                            e[c] = 1.0;
                            let mut cvc_tmp = c_vc.clone();
                            let _ = dense_cholesky_solve(&mut cvc_tmp, &mut e, n_c);
                            for c2 in 0..n_c { real_inv[c * n_c + c2] = e[c2]; }
                        }
                        
                        apply_kriging_correction(&mut u, &v_c, &real_inv, constr, n_latent, n_c);
                        
                        for j in 0..n_fixed {
                            let mut vj = v[j * n_latent .. (j+1)*n_latent].to_vec();
                            apply_kriging_correction(&mut vj, &v_c, &real_inv, constr, n_latent, n_c);
                            for k in 0..n_latent { v[k + j * n_latent] = vj[k]; }
                        }
                    }
                }
            }

            let mut s_mat = vec![0.0_f64; n_fixed * n_fixed];
            for j1 in 0..n_fixed {
                for j2 in 0..n_fixed {
                    let mut xtwx = 0.0;
                    for i in 0..n_data {
                        xtwx += x_m[i + j1 * n_data] * curv_data[i] * x_m[i + j2 * n_data];
                    }
                    if j1 == j2 { xtwx += PRIOR_PREC_BETA; }
                    
                    let mut wcv = 0.0;
                    for k in 0..n_latent {
                        wcv += w_cross[k + j1 * n_latent] * v[k + j2 * n_latent];
                    }
                    s_mat[j1 * n_fixed + j2] = xtwx - wcv;
                }
            }

            let mut b_s = vec![0.0_f64; n_fixed];
            for j in 0..n_fixed {
                let mut wcu = 0.0;
                for k in 0..n_latent { wcu += w_cross[k + j * n_latent] * u[k]; }
                b_s[j] = b_beta[j] - wcu;
            }

            let s_mat_bkp = s_mat.clone();
            if let Err(_) = dense_cholesky_solve(&mut s_mat, &mut b_s, n_fixed) {
                return Err(crate::error::InlaError::NotPositiveDefiniteContext(format!("Schur S_mat loop singular, diag: {:?}", s_mat_bkp[0])));
            }
            for j in 0..n_fixed { beta[j] = b_s[j]; }

            for k in 0..n_latent {
                let mut vb = 0.0;
                for j in 0..n_fixed { vb += v[k + j * n_latent] * beta[j]; }
                x[k] = u[k] - vb;
            }

            let mut delta_max = 0.0_f64;
            for (a, b_val) in x.iter().zip(x_old.iter()) { delta_max = delta_max.max((a - b_val).abs()); }
            for (a, b_val) in beta.iter().zip(beta_old.iter()) { delta_max = delta_max.max((a - b_val).abs()); }
            
            if delta_max < tol { break; }
        }

        let aug_inv  = self.solver.selected_inverse()?;
        let col_ptr  = aug_inv.symbolic().col_ptr();
        let row_idx  = aug_inv.symbolic().row_idx();
        let all_vals = aug_inv.val();

        let diag_aug_inv: Vec<f64> = (0..n_latent).map(|j| {
            let pos = row_idx[col_ptr[j]..col_ptr[j + 1]].binary_search(&j).unwrap();
            all_vals[col_ptr[j] + pos]
        }).collect();

        let mut v = vec![0.0_f64; n_latent * n_fixed];
        for j in 0..n_fixed {
            let mut v_col = final_w_cross[j * n_latent .. (j+1) * n_latent].to_vec();
            self.solver.solve_llt(&mut v_col);
            for k in 0..n_latent { v[k + j * n_latent] = v_col[k]; }
        }

        let mut s_mat = vec![0.0_f64; n_fixed * n_fixed];
        for j1 in 0..n_fixed {
            for j2 in 0..n_fixed {
                let mut xtwx = 0.0;
                for i in 0..n_data {
                    xtwx += x_m[i + j1 * n_data] * final_w_data[i] * x_m[i + j2 * n_data];
                }
                if j1 == j2 { xtwx += PRIOR_PREC_BETA; }
                let mut wcv = 0.0;
                for k in 0..n_latent {
                    wcv += final_w_cross[k + j1 * n_latent] * v[k + j2 * n_latent];
                }
                s_mat[j1 * n_fixed + j2] = xtwx - wcv;
            }
        }
        
        let mut dummy_b = vec![0.0_f64; n_fixed];
        let schur_log_det = dense_cholesky_solve(&mut s_mat, &mut dummy_b, n_fixed).map_err(|_| crate::error::InlaError::NotPositiveDefiniteContext("Schur S_mat final singular".to_string()))?;

        Ok((beta, x, log_det_aug, diag_aug_inv, schur_log_det))
    }

    pub fn find_mode_with_logdet(&mut self, model: &crate::inference::InlaModel<'_>, theta: &[f64], max_iter: usize, tol: f64) -> Result<(Vec<f64>, f64), InlaError> {
        let (x, ld, _) = self.find_mode_with_inverse(model, theta, &[], max_iter, tol)?;
        Ok((x, ld))
    }

    pub fn find_mode(&mut self, model: &crate::inference::InlaModel<'_>, theta: &[f64], max_iter: usize, tol: f64) -> Result<Vec<f64>, InlaError> {
        let (x, _) = self.find_mode_with_logdet(model, theta, max_iter, tol)?;
        Ok(x)
    }

    pub fn solve(&self, rhs: &mut [f64]) { self.solver.solve_llt(rhs); }
    pub fn log_det(&self) -> f64 { self.log_det }
    pub fn n(&self) -> usize { self.graph.n() }

    pub fn quadratic_form_x(&self, qfunc: &dyn QFunc, theta_model: &[f64], x: &[f64]) -> f64 {
        let n = self.n();
        let diag: f64 = (0..n).map(|i| qfunc.eval(i, i, theta_model) * x[i] * x[i]).sum();
        let offdiag: f64 = qfunc.graph().iter_upper_triangle().map(|(i, j)| 2.0 * qfunc.eval(i, j, theta_model) * x[i] * x[j]).sum();
        diag + offdiag
    }
}

// Native dense Cholesky implementation for tiny exact K x K matrices.
fn dense_cholesky_solve(a: &mut [f64], b: &mut [f64], n: usize) -> Result<f64, InlaError> {
    let mut log_det = 0.0;
    
    let mut a_bkp = a.to_vec();
    let mut success = true;

    for i in 0..n {
        for j in 0..=i {
            let mut sum = a[i * n + j];
            for k in 0..j { sum -= a[i * n + k] * a[j * n + k]; }
            if i == j {
                if sum <= 1e-12 { success = false; break; }
                let l_ii = sum.sqrt();
                a[i * n + j] = l_ii;
                log_det += 2.0 * l_ii.ln();
            } else {
                a[i * n + j] = sum / a[j * n + j];
            }
        }
        if !success { break; }
    }
    
    if !success {
        // Ridge fallback for unidentifiable singular overlaps
        log_det = 0.0;
        for i in 0..n { a_bkp[i * n + i] += 1.0; } // Heavy regularization Prior
        for i in 0..n {
            for j in 0..=i {
                let mut sum = a_bkp[i * n + j];
                for k in 0..j { sum -= a_bkp[i * n + k] * a_bkp[j * n + k]; }
                if i == j {
                    if sum <= 1e-12 { return Err(InlaError::NotPositiveDefinite); }
                    let l_ii = sum.sqrt();
                    a_bkp[i * n + j] = l_ii;
                    log_det += 2.0 * l_ii.ln();
                } else {
                    a_bkp[i * n + j] = sum / a_bkp[j * n + j];
                }
            }
        }
        a.copy_from_slice(&a_bkp);
    }
    
    for i in 0..n {
        let mut sum = b[i];
        for k in 0..i { sum -= a[i * n + k] * b[k]; }
        b[i] = sum / a[i * n + i];
    }
    for i in (0..n).rev() {
        let mut sum = b[i];
        for k in (i + 1)..n { sum -= a[k * n + i] * b[k]; }
        b[i] = sum / a[i * n + i];
    }
    Ok(log_det)
}

struct AugmentedQFunc<'a> {
    inner: &'a dyn QFunc,
    atwa:  &'a std::collections::HashMap<(usize, usize), f64>,
}

impl QFunc for AugmentedQFunc<'_> {
    fn graph(&self) -> &Graph { self.inner.graph() }
    fn eval(&self, i: usize, j: usize, theta: &[f64]) -> f64 {
        let mut base = self.inner.eval(i, j, theta);
        if i == j && !self.inner.is_proper() {
            base += 1e-6; // Intrinsic regularization
        }
        let (min_j, max_j) = if i < j { (i, j) } else { (j, i) };
        base + self.atwa.get(&(min_j, max_j)).copied().unwrap_or(0.0)
    }
    fn n_hyperparams(&self) -> usize { self.inner.n_hyperparams() }
}


// Kriging solver: u_new = u_old - V_c (C V_c)^-1 C u_old
fn apply_kriging_correction(
    u: &mut [f64],
    v_c: &[f64], // n_latent x n_constr
    c_vc_inv: &[f64], // n_constr x n_constr
    constr: &[f64], // n_constr x n_latent
    n_latent: usize,
    n_constr: usize,
) {
    let mut cu = vec![0.0_f64; n_constr];
    for c in 0..n_constr {
        for i in 0..n_latent {
            cu[c] += constr[c * n_latent + i] * u[i];
        }
    }
    let mut lambda = vec![0.0_f64; n_constr];
    for c1 in 0..n_constr {
        for c2 in 0..n_constr {
            lambda[c1] += c_vc_inv[c1 * n_constr + c2] * cu[c2];
        }
    }
    for i in 0..n_latent {
        for c in 0..n_constr {
            u[i] -= v_c[c * n_latent + i] * lambda[c];
        }
    }
}
