# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustyINLA_wrappers", use_symbols = TRUE, package_name = "rustyINLA")

#' @usage NULL
#' @useDynLib rustyINLA, .registration = TRUE
NULL

#' Execute rust-inla backend from R.
#'
#' @param data A numeric array of length N (the response y).
#' @param model_type String identifier ("iid", "rw1", "ar1").
#' @param likelihood_type String identifier ("gaussian", "poisson", "gamma").
#' @param intercept Boolean to estimate global beta0.
#' @export
rust_inla_run <- function(data, model_type, likelihood_type, intercept, n_latent_arg, x_idx_arg) .Call(wrap__rust_inla_run, data, model_type, likelihood_type, intercept, n_latent_arg, x_idx_arg)


# nolint end
