# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustyINLA_wrappers", use_symbols = TRUE, package_name = "rustyINLA")

#' @usage NULL
#' @useDynLib rustyINLA, .registration = TRUE
NULL

#' Execute rust-inla backend from R.
#'
#' @param a_i_arg Array of obs integers
#' @export
rust_inla_run <- function(data, model_types_arg, likelihood_type, fixed_matrix_arg, n_fixed_arg, n_latent_arg, a_i_arg, a_j_arg, a_x_arg) .Call(wrap__rust_inla_run, data, model_types_arg, likelihood_type, fixed_matrix_arg, n_fixed_arg, n_latent_arg, a_i_arg, a_j_arg, a_x_arg)


# nolint end
